### ISSUE TITLE
Is Sankey broken?

### ISSUE THREAD

**Issue by svken** [simwrapper/simwrapper.github.io#2]
I have the following Sankey Yaml but sadly all i get is an empty screen with the button "änderungen anzeigen" in the left corner. When i dont use, props it shows nothing. Whats also interesting is that the sankey plot in the example files is also broken.

```
header:
  tab: "Summary"
  title: "Top-Level Summary Statistics"
  description: "SimWrapper dashboard example"

  scores2:
    - type: "sankey"
      title: "Score statistics"
      description: "by iteration"
      height: 8
      props:
          csv: "output/mode_shift.csv"
          columns: ['from','to','Value']
```

i have this mode_shit csv:

`from;to;Value
car;pt;399
pt;pt;1272
ride;ride;1079
car;bike;1352
ride;bike;150
car;car;2022
pt;bike;833
bike;bike;710
bike;pt;114
bike;car;208
ride;car;50
ride;pt;55
pt;car;421
walk;walk;1297
ride;walk;51
car;walk;388
walk;bike;239
bike;walk;97
walk;car;92
walk;pt;42
pt;ride;3`

Thank you for your help!
